// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADP9BtM8FNhtCGpsOa5EXemci1GQ-ica0',
    appId: '1:1063897647857:web:9d4073ff02176ff826f750',
    messagingSenderId: '1063897647857',
    projectId: 'inventory-management-sys-a3f78',
    authDomain: 'inventory-management-sys-a3f78.firebaseapp.com',
    storageBucket: 'inventory-management-sys-a3f78.firebasestorage.app',
    measurementId: 'G-N0EJW4TEW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOGxaR2spa5Xwaj3BIc_JwtmxhYOvqPbc',
    appId: '1:1063897647857:android:ac3faf838acc676126f750',
    messagingSenderId: '1063897647857',
    projectId: 'inventory-management-sys-a3f78',
    storageBucket: 'inventory-management-sys-a3f78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ94luvyGJ5P2ijN2QmgeAQBNSekn5wJs',
    appId: '1:1063897647857:ios:c2b1b741388b2c9126f750',
    messagingSenderId: '1063897647857',
    projectId: 'inventory-management-sys-a3f78',
    storageBucket: 'inventory-management-sys-a3f78.firebasestorage.app',
    iosBundleId: 'com.example.invetoryManagement1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ94luvyGJ5P2ijN2QmgeAQBNSekn5wJs',
    appId: '1:1063897647857:ios:c2b1b741388b2c9126f750',
    messagingSenderId: '1063897647857',
    projectId: 'inventory-management-sys-a3f78',
    storageBucket: 'inventory-management-sys-a3f78.firebasestorage.app',
    iosBundleId: 'com.example.invetoryManagement1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADP9BtM8FNhtCGpsOa5EXemci1GQ-ica0',
    appId: '1:1063897647857:web:aae8dc7b7a7ad9f026f750',
    messagingSenderId: '1063897647857',
    projectId: 'inventory-management-sys-a3f78',
    authDomain: 'inventory-management-sys-a3f78.firebaseapp.com',
    storageBucket: 'inventory-management-sys-a3f78.firebasestorage.app',
    measurementId: 'G-ER0SKCWL6C',
  );
}
